export const dummyResumeData = [
    {
        id: 1,
        date: "18/04/2022",
        location: "Rumah Sakit Maju Jaya",
        diagnose: "E11.9 - Diabetes mellitus",
        recordNumber: "12345",
        nik: "1234567890",
        patientType: "Inpatient",
        patientName: "Jimmy Daniel",
        doctorName: "Dr. Ali",
        polyName: "Endocrinology",
        anamnesis: "Patient presented with high blood sugar levels...",
        medicine: "Insulin",
    },
    {
        id: 2,
        date: "04/04/2022",
        location: "Puskesmas Serpong",
        diagnose: "E11.9 - Diabetes mellitus",
        recordNumber: "54321",
        nik: "0987654321",
        patientType: "Outpatient",
        patientName: "Jimmy Daniel",
        doctorName: "Dr. Ali",
        polyName: "Internal Medicine",
        anamnesis: "Patient complained of increased thirst and frequent urination...",
        medicine: "Metformin",
    },
    {
        id: 3,
        date: "21/03/2022",
        location: "Klinik Makmur Jaya",
        diagnose: "E11.9 - Diabetes mellitus",
        recordNumber: "98765",
        nik: "6789012345",
        patientType: "Outpatient",
        patientName: "Jimmy Daniel",
        doctorName: "Dr. Ali",
        polyName: "Family Medicine",
        anamnesis: "Patient has a family history of diabetes...",
        medicine: "Glipizide",
    },
    {
        id: 4,
        date: "07/03/2022",
        location: "Rumah Sakit Medika",
        diagnose: "E11.9 - Diabetes mellitus",
        recordNumber: "56789",
        nik: "3456789012",
        patientType: "Inpatient",
        patientName: "Jimmy Daniel",
        doctorName: "Dr. Ali",
        polyName: "Endocrinology",
        anamnesis: "Patient admitted with diabetic ketoacidosis...",
        medicine: "NovoLog",
    },
    {
        id: 5,
        date: "22/02/2022",
        location: "Puskesmas Serpong",
        diagnose: "E11.9 - Diabetes mellitus",
        recordNumber: "23456",
        nik: "4567890123",
        patientType: "Outpatient",
        patientName: "Jimmy Daniel",
        doctorName: "Dr. Ali",
        polyName: "Internal Medicine",
        anamnesis: "Patient needs a refill of her diabetes medication...",
        medicine: "Acarbose",
    },
    {
        id: 6,
        date: "7/02/2022",
        location: "Rumah Sakit Maju Jaya",
        diagnose: "A75 - Demam tifus",
        recordNumber: "67890",
        nik: "7890123456",
        patientType: "Inpatient",
        patientName: "Jimmy Daniel",
        doctorName: "Dr. Ali",
        polyName: "Infectious Diseases",
        anamnesis: "Patient presented with high fever and abdominal pain...",
        medicine: "Typhoid vaccine",
    },
    {
        id: 7,
        date: "24/01/2022",
        location: "Puskesmas Serpong",
        diagnose: "A75 - Demam tifus",
        recordNumber: "78901",
        nik: "8901234567",
        patientType: "Outpatient",
        patientName: "Jimmy Daniel",
        doctorName: "Dr. Ali",
        polyName: "Internal Medicine",
        anamnesis: "Patient complained of fever, headache, and body aches...",
        medicine: "Antibiotics",
    },
    {
        id: 8,
        date: "07/01/2022",
        location: "Klinik Makmur Jaya",
        diagnose: "Z23.2 - Imunisasi BCG",
        recordNumber: "34567",
        nik: "5678901234",
        patientType: "Outpatient",
        patientName: "Jimmy Daniel",
        doctorName: "Dr. Ali",
        polyName: "Pediatrics",
        anamnesis: "Patient brought in for routine BCG vaccination...",
        medicine: "BCG vaccine",
    }
];
