export const dummyResumeData = [
    {
        id: 1,
        date: "18/04/2022",
        location: "Rumah Sakit Maju Jaya",
        diagnose: "E11.9 - Diabetes mellitus",
        record_number: "",
        nik: "",
        patient_type: "",
        patient_name: "",
        doctor_name: "",
        poly_name: "",
        anamnesis: "",
        medicine: "",
    },
    {
        id: 2,
        date: "04/04/2022",
        location: "Puskesmas Serpong",
        diagnose: "E11.9 - Diabetes mellitus",
        record_number: "",
        nik: "",
        patient_type: "",
        patient_name: "",
        doctor_name: "",
        poly_name: "",
        anamnesis: "",
        medicine: "",
    },
    {
        id: 3,
        date: "21/03/2022",
        location: "Klinik Makmur Jaya",
        diagnose: "E11.9 - Diabetes mellitus",
        record_number: "",
        nik: "",
        patient_type: "",
        patient_name: "",
        doctor_name: "",
        poly_name: "",
        anamnesis: "",
        medicine: "",
    },
    {
        id: 4,
        date: "07/03/2022",
        location: "Rumah Sakit Medika",
        diagnose: "E11.9 - Diabetes mellitus",
        record_number: "",
        nik: "",
        patient_type: "",
        patient_name: "",
        doctor_name: "",
        poly_name: "",
        anamnesis: "",
        medicine: "",
    },
    {
        id: 5,
        date: "22/02/2022",
        location: "Puskesmas Serpong",
        diagnose: "E11.9 - Diabetes mellitus",
        record_number: "",
        nik: "",
        patient_type: "",
        patient_name: "",
        doctor_name: "",
        poly_name: "",
        anamnesis: "",
        medicine: "",
    },
    {
        id: 6,
        date: "7/02/2022",
        location: "Rumah Sakit Maju Jaya",
        diagnose: "A75 - Demam tifus",
        record_number: "",
        nik: "",
        patient_type: "",
        patient_name: "",
        doctor_name: "",
        poly_name: "",
        anamnesis: "",
        medicine: "",
    },
    {
        id: 7,
        date: "24/01/2022",
        location: "Puskesmas Serpong",
        diagnose: "A75 - Demam tifus",
        record_number: "",
        nik: "",
        patient_type: "",
        patient_name: "",
        doctor_name: "",
        poly_name: "",
        anamnesis: "",
        medicine: "",
    },
    {
        id: 8,
        date: "07/01/2022",
        location: "Klinik Makmur Jaya",
        diagnose: "Z23.2 - Imunisasi BCG",
        record_number: "",
        nik: "",
        patient_type: "",
        patient_name: "",
        doctor_name: "",
        poly_name: "",
        anamnesis: "",
        medicine: "",
    }
];